import Head from 'next/head';
import { Flex, Box } from '@chakra-ui/react';
import Banner from '@/components/Banner/Banner';
import { baseEndpointUrl, fetchAPI } from '@/utils/fetchAPI';
import { APIResponse, Hit } from '@/utils/APIResponse.model';
import Property from '@/components/Property/Property';

export default function Home({propertiesForSale, propertiesForRent} : {propertiesForSale: Hit[], propertiesForRent: Hit[]}) {
  console.log(propertiesForSale, propertiesForRent)
  return (
    <>
      <Head>
        <title>Nextjs Realtor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <h1>Hello dood</h1>
        <Banner 
          purpose="Location"
          title1="Maison & Appartements à louer pour"
          title2="Tout le monde"
          desc1="Chercher des appartements, villas, maisons"
          desc2="et plus..."
          buttonText="Voir les offres"
          linkName="/search?purpose=for-rent"
          imageUrl="https://bayut-production.s3.eu-central-1.amazonaws.com/image/145426814/33973352624c48628e41f2ec460faba4"
        />
        <Flex flexWrap="wrap">
          {propertiesForRent.map((property: Hit) => <Property property={property} key={property.id}/>)}
        </Flex>
        <Banner 
          purpose="Achat"
          title1="Trouver, acheter et devenir propriétaire"
          title2="de sa maison"
          desc1="Chercher des appartements, villas, maisons"
          desc2="et plus..."
          buttonText="Voir les offres"
          linkName="/search?purpose=for-sale"
          imageUrl="https://bayut-production.s3.eu-central-1.amazonaws.com/image/145426814/33973352624c48628e41f2ec460faba4"
        />
        <Flex flexWrap="wrap">
          {propertiesForSale.map((property: Hit) => <Property property={property} key={property.id}/>)}
        </Flex>
      </Box>
    </>
  )
}

export async function getStaticProps(){
  const propertyForSale : APIResponse = await fetchAPI(`${baseEndpointUrl}/properties/list?locationExternalIDs=5002&purpose=for-sale&hitsPerPage=6`);
  const propertyForRent : APIResponse = await fetchAPI(`${baseEndpointUrl}/properties/list?locationExternalIDs=5002&purpose=for-rent&hitsPerPage=6`);

  return {
    props: {
      propertiesForSale: propertyForSale?.hits,
      propertiesForRent: propertyForRent?.hits
    }
  }
}
