import Link from 'next/link';
import Image from 'next/image';
import Head from 'next/head';
import { Flex, Box, Text, Button } from '@chakra-ui/react';
import Banner from '@/components/Molecules/Banner/Banner';

export default function Home() {
  return (
    <>
      <Head>
        <title>Nextjs Realtor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <h1>Hello dood</h1>
        <Banner 
          purpose="Location"
          title1="Maison & Appartements à louer pour"
          title2="Tout le monde"
          desc1="Chercher des appartements, villas, maisons"
          desc2="et plus..."
          buttonText="Voir les offres"
          linkName="/search?purpose=location"
          imageUrl="https://bayut-production.s3.eu-central-1.amazonaws.com/image/145426814/33973352624c48628e41f2ec460faba4"
        />
        <Banner 
          purpose="Achat"
          title1="Trouver, acheter et devenir propriétaire"
          title2="de sa maison"
          desc1="Chercher des appartements, villas, maisons"
          desc2="et plus..."
          buttonText="Voir les offres"
          linkName="/search?purpose=achat"
          imageUrl="https://bayut-production.s3.eu-central-1.amazonaws.com/image/145426814/33973352624c48628e41f2ec460faba4"
        />
      </Box>
    </>
  )
}
